auto-create-game: true

world:
  name: "world"
  jail: "-4.5,12,-36.5"
  lobby: "0,10,0"
  respawnBlock: "-4,12,44"
  spawn:
    - "-5.5,12,-13.5"
    - "12.5,12,-12"
  killerSpawn:
    - "1.5,12,4.5"
  generator:
    - "7.5,12,24.5"
    - "7.5,12,43.5"
    - "-8.5,12,43.5"
    - "-8.5,12,24.5"
  fish:
    - "15.5,13,50.5"
    - "-18.5,13,50.5"
  gateLever:
    - "-19.5,12,-53.5"